### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by b4b857f6ee** [StamusNetworks/stamus_for_splunk#2]
Hello 👍 

I think you have to already create the local folder, all the other Splunk app have this. And it's can be cool to configure the token and IP of scirius with the interactive menu in the app directly in splunk, like a post-configuration, instead of going in cli :).
And add a test boutton to test the configuration.

**Comment by regit** [comment]
Thanks for the tip on local directory. And yes, getting interactive menu in app will be far better than cli.

**Comment by b4b857f6ee** [comment]
This is a normal behavior after install it?
We didn't jump directly into the first Dashboard and we didn't have a menu with all the dashboard?
![image](https://user-images.githubusercontent.com/36012515/95191687-604ab480-07d1-11eb-9d89-053028973981.png)

**Comment by regit** [comment]
Yes, this is the current behavior and getting a dashboard view at first would be better indeed.

**Comment by b4b857f6ee** [comment]
Like this? 

![image](https://user-images.githubusercontent.com/36012515/95194676-d6511a80-07d5-11eb-988b-2bc9749fda5f.png)


![image](https://user-images.githubusercontent.com/36012515/95194755-f1bc2580-07d5-11eb-8c81-6b75d28a9204.png)

**Comment by b4b857f6ee** [comment]
I think you need to protect your repository because i can modify everything without a pull... strange...

**Comment by regit** [comment]
Hello,

What do you mean here ?

**Comment by b4b857f6ee** [comment]
I am not really an advanced user on github but i fork the repo and modify one file and i see the file modify in your master. I think you have to approve the modifcation inside your master before no?

**Comment by regit** [comment]
If you look at the PR, it is coming from your repository: https://github.com/StamusNetworks/stamus_for_splunk/pull/3

The master on StamusNetworks account is unchanged.

**Comment by b4b857f6ee** [comment]
Oh ok, my bad!

**Comment by regit** [comment]
@b4b857f6ee can I close this issue ?

**Comment by b4b857f6ee** [comment]
Yes :)
