### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by b4b857f6ee** [StamusNetworks/stamus_for_splunk#4]
Hello,

Splunk v8.0.6
SNApp : 0.9.4

How can i check manualy the API, with some kind of curl command or something?

![image](https://user-images.githubusercontent.com/36012515/95197101-59c03b00-07d9-11eb-8563-c5fa0a15e962.png)

I got this on the selks side :

==> /var/log/nginx/scirius.access.log <==
my ip - - [06/Oct/2020:07:09:45] "GET /rest/appliances/host_id/?page=1 HTTP/1.1" 404 2991 "-" "python-requests/2.22.0"

**Comment by b4b857f6ee** [comment]
I try the api and the /rest work i get something but /rest/appliances/host_id/?page=1  /rest/appliances/host_id and /rest/appliances/ return nothing

**Comment by regit** [comment]
The commands are currently only for Scirius Security Platform and are not using REST API entry points available in Scirius Community Edition. There may be some commands using features available in CE soon.

**Comment by b4b857f6ee** [comment]
Ok thank you. So which dashboard i can expect to be working?

**Comment by regit** [comment]
All the Suricata ones do not require SSP.

**Comment by b4b857f6ee** [comment]
Ok, so maybe i can do 2 menus, the first for the free edition and the other for the "premium" edition. Let me try it.

**Comment by b4b857f6ee** [comment]
I can close this one because i got the answer 👍
