### ISSUE TITLE
Add index selection support

### ISSUE THREAD

**Issue by regit** [StamusNetworks/stamus_for_splunk#5]
User would like to select on index where to get the data from. An easy way to this is to do it via `ssp.conf`

**Comment by JSkier21** [comment]
Thank you @regit, moving this discussion here. 

Was, and still am thinking out loud here, perhaps support for an inputs.conf makes more sense to line up with the splunk app ecosphere? Or perhaps get it rolling quickly with ssp.conf for now, feature enhancement for inputs.conf later.

**Comment by regit** [comment]
OK @JSkier21, I will check what is the Splunk-iest way of doing this.

**Comment by regit** [comment]
#6 is merged so next release will feature this.
